FROM maven

WORKDIR /

# Config and data
RUN mkdir hawk

COPY pom.xml /hawk/pom.xml
COPY qa.datasets /hawk/qa.datasets/
COPY qa.commons /hawk/qa.commons/
COPY qa.annotation /hawk/qa.annotation/
COPY qa.systems /hawk/qa.systems
COPY qa.ml /hawk/qa.ml
COPY qa.seqa /hawk/qa.seqa

COPY qa.hawk /hawk/qa.hawk/


# Build all dependencies from multi-module
WORKDIR /hawk/
#RUN mvn clean install -DskipTests -Dmaven.javadoc.skip=true

# Execute main hawk
WORKDIR /hawk/qa.hawk
EXPOSE 8181
#CMD ["mvn", "clean", "install", "spring-boot:run", "-DskipTests", "-Dmaven.javadoc.skip=true"]
CMD ["mvn", "spring-boot:run"]
