## LOADING INTO FUSEKI
join -1 1 -2 1 labels_en.ttl.sorted redirects_transitive_en.ttl.sorted  > join.tsv
cat join.tsv | awk '{sub("<http://www.w3.org/2000/01/rdf-schema#label>","",$0);sub("<http://dbpedia.org/ontology/wikiPageRedirects>","",$0); sub(" .  "," ",$0); print $0}'| awk -F">  \"" '{print "\""$2 }'| awk -F"@en <" '{print $2 " <http://www.w3.org/2000/01/rdf-schema#label> " $1}' | awk '{sub(" . "," ",$0);  print $0 " . " }' > join.clean

/data/r.usbeck/Dropbox/apache-jena-2.12.1/bin/tdbloader2 --loc=/data/r.usbeck/dbpediatbd dbpedia_3.9.owl disambiguations_en.ttl instance_types_en.ttl long_abstracts_en.ttl pagerank_en_3.9.ttl pnd_en.ttl en_surface_forms.newer labels_en.ttl mappingbased_properties_en.ttl persondata_en.ttl redirect_resolved.ttl.newer specific_mappingbased_properties_en.ttl
java -Xmx6G -cp /data/r.usbeck/Dropbox/jena-fuseki-1.1.1/fuseki-server.jar jena.textindexer --desc=/data/r.usbeck/Dropbox/hawk_assembler.ttl

## QUERYING FUSEKI
/Users/ricardousbeck/Dropbox/apache-jena-2.12.1/bin/tdbquery  --loc /Users/ricardousbeck/dbpediatbd/ "SELECT * WHERE {?s ?p ?o.} LIMIT 10" 

/Users/ricardousbeck/Dropbox/apache-jena-2.12.1/bin/tdbquery  --loc /Users/ricardousbeck/dbpediatbd/  --desc=/Users/ricardousbeck/Dropbox/hawk_assembler.ttl "SELECT * WHERE {?s <http://dbpedia.org/ontology/abstract> ?o.} LIMIT 10"

/Users/ricardousbeck/Dropbox/apache-jena-2.12.1/bin/tdbquery --loc /Users/ricardousbeck/dbpediatbd/ "PREFIX text: <http://jena.apache.org/text#> SELECT * WHERE {?s ?p ?o. ?o text:query (<http://dbpedia.org/ontology/abstract> 'anti-apartheid activist' )} LIMIT 10"

## STARTING FUSEKI
./fuseki-server --conf=/Users/ricardousbeck/Dropbox/hawk_assembler.ttl

## TEST QUERIES
PREFIX text:    <http://jena.apache.org/text#> 
SELECT *
{ 
?s text:query (<http://dbpedia.org/ontology/abstract> 'Mandela') 
}LIMIT 10

SELECT * WHERE {?s ?p ?o} LIMIT 10
